# Generated by Django 2.0.7 on 2018-09-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataterminal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldMapModel',
            new_name='FieldMap',
        ),
    ]
