# Generated by Django 2.0.7 on 2018-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataterminal', '0002_auto_20180921_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
